-- Create table for conversations
CREATE TABLE `conversations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL COMMENT 'Title for group conversations, NULL for direct messages',
  `type` enum('direct','group','application') NOT NULL COMMENT 'direct: 1-on-1, group: multiple participants, application: related to application',
  `created_by` int(11) NOT NULL,
  `application_id` int(11) DEFAULT NULL COMMENT 'If conversation is related to an application',
  `organization_id` int(11) NOT NULL,
  `booking_id` int(11) DEFAULT NULL,
  `is_archived` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_message_at` datetime DEFAULT NULL COMMENT 'Timestamp of the last message',
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `application_id` (`application_id`),
  KEY `idx_conversations_type` (`type`),
  KEY `idx_conversations_last_message` (`last_message_at`),
  KEY `idx_conversations_organization` (`organization_id`),
  KEY `idx_conversations_booking` (`booking_id`),
  CONSTRAINT `conversations_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `conversations_application_id_fk` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON DELETE SET NULL,
  CONSTRAINT `conversations_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `conversations_booking_id_fk` FOREIGN KEY (`booking_id`) REFERENCES `bookings` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create table for conversation participants
CREATE TABLE `conversation_participants` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conversation_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `role` enum('member','admin','applicant','consultant','team_member') NOT NULL,
  `is_muted` tinyint(1) NOT NULL DEFAULT 0,
  `joined_at` datetime NOT NULL DEFAULT current_timestamp(),
  `left_at` datetime DEFAULT NULL COMMENT 'When participant left the conversation',
  PRIMARY KEY (`id`),
  UNIQUE KEY `conversation_user` (`conversation_id`, `user_id`),
  KEY `user_id` (`user_id`),
  KEY `idx_participants_role` (`role`),
  CONSTRAINT `participants_conversation_id_fk` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `participants_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create messages table
CREATE TABLE `messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conversation_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL COMMENT 'Sender of the message',
  `message` text NOT NULL,
  `is_system_message` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Indicates if message was generated by system',
  `parent_message_id` int(11) DEFAULT NULL COMMENT 'For message replies/threads',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `conversation_id` (`conversation_id`),
  KEY `user_id` (`user_id`),
  KEY `parent_message_id` (`parent_message_id`),
  KEY `idx_messages_created_at` (`created_at`),
  CONSTRAINT `messages_conversation_id_fk` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `messages_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `messages_parent_message_id_fk` FOREIGN KEY (`parent_message_id`) REFERENCES `messages` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create message read status table
CREATE TABLE `message_read_status` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL COMMENT 'User who read the message',
  `read_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `message_user` (`message_id`, `user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `read_status_message_id_fk` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `read_status_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create message attachments table
CREATE TABLE `message_attachments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_path` varchar(255) NOT NULL,
  `file_type` varchar(100) NOT NULL,
  `file_size` int(11) NOT NULL COMMENT 'Size in bytes',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`),
  KEY `idx_attachments_file_type` (`file_type`),
  CONSTRAINT `attachments_message_id_fk` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create message reactions table
CREATE TABLE `message_reactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `reaction` varchar(50) NOT NULL COMMENT 'Emoji or reaction type',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `message_user_reaction` (`message_id`, `user_id`, `reaction`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `reactions_message_id_fk` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reactions_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create conversation typing status table
CREATE TABLE `conversation_typing` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conversation_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `is_typing` tinyint(1) NOT NULL DEFAULT 0,
  `last_updated` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `conversation_user` (`conversation_id`, `user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `typing_conversation_id_fk` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `typing_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Function to check unread messages count for a user
DELIMITER //
CREATE FUNCTION get_unread_messages_count(p_user_id INT) 
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE v_count INT;
    
    SELECT COUNT(m.id) INTO v_count
    FROM messages m
    JOIN conversation_participants cp ON m.conversation_id = cp.conversation_id
    LEFT JOIN message_read_status mrs ON m.id = mrs.message_id AND mrs.user_id = p_user_id
    WHERE cp.user_id = p_user_id
      AND m.user_id != p_user_id
      AND m.deleted_at IS NULL
      AND cp.left_at IS NULL
      AND mrs.id IS NULL;
    
    RETURN v_count;
END //
DELIMITER ;

-- Trigger to update conversation last_message_at timestamp
DELIMITER //
CREATE TRIGGER after_message_insert
AFTER INSERT ON messages
FOR EACH ROW
BEGIN
    -- Update the conversation's last_message_at timestamp
    UPDATE conversations
    SET last_message_at = NEW.created_at
    WHERE id = NEW.conversation_id;
    
    -- Automatically mark message as read by the sender
    INSERT INTO message_read_status (message_id, user_id, read_at)
    VALUES (NEW.id, NEW.user_id, NOW());
    
    -- Remove typing status for the message sender
    UPDATE conversation_typing
    SET is_typing = 0, last_updated = NOW()
    WHERE conversation_id = NEW.conversation_id AND user_id = NEW.user_id;
END //
DELIMITER ;

-- Procedure to create a direct conversation between two users
DELIMITER //
CREATE PROCEDURE create_direct_conversation(
    IN p_creator_id INT,
    IN p_participant_id INT,
    OUT p_conversation_id INT
)
BEGIN
    DECLARE v_existing_conv_id INT;
    DECLARE v_creator_role VARCHAR(10);
    DECLARE v_participant_role VARCHAR(10);
    
    -- Check if direct conversation already exists between these users
    SELECT c.id INTO v_existing_conv_id
    FROM conversations c
    JOIN conversation_participants cp1 ON c.id = cp1.conversation_id
    JOIN conversation_participants cp2 ON c.id = cp2.conversation_id
    WHERE c.type = 'direct'
      AND cp1.user_id = p_creator_id
      AND cp2.user_id = p_participant_id
      AND cp1.left_at IS NULL
      AND cp2.left_at IS NULL
      AND c.deleted_at IS NULL
    LIMIT 1;
    
    IF v_existing_conv_id IS NOT NULL THEN
        -- Return existing conversation ID
        SET p_conversation_id = v_existing_conv_id;
    ELSE
        -- Get user roles
        SELECT user_type INTO v_creator_role FROM users WHERE id = p_creator_id;
        SELECT user_type INTO v_participant_role FROM users WHERE id = p_participant_id;
        
        -- Start transaction
        START TRANSACTION;
        
        -- Create new conversation
        INSERT INTO conversations (type, created_by, created_at, updated_at, last_message_at)
        VALUES ('direct', p_creator_id, NOW(), NOW(), NOW());
        
        -- Get the new conversation ID
        SET p_conversation_id = LAST_INSERT_ID();
        
        -- Add creator as participant
        INSERT INTO conversation_participants (conversation_id, user_id, role, joined_at)
        VALUES (p_conversation_id, p_creator_id, v_creator_role, NOW());
        
        -- Add the other participant
        INSERT INTO conversation_participants (conversation_id, user_id, role, joined_at)
        VALUES (p_conversation_id, p_participant_id, v_participant_role, NOW());
        
        -- Add system message indicating conversation creation
        INSERT INTO messages (conversation_id, user_id, message, is_system_message, created_at)
        VALUES (p_conversation_id, p_creator_id, 'Conversation started', 1, NOW());
        
        COMMIT;
    END IF;
END //
DELIMITER ;

-- Procedure to create a group conversation
DELIMITER //
CREATE PROCEDURE create_group_conversation(
    IN p_creator_id INT,
    IN p_title VARCHAR(255),
    IN p_application_id INT,
    OUT p_conversation_id INT
)
BEGIN
    DECLARE v_creator_role VARCHAR(10);
    
    -- Get creator role
    SELECT user_type INTO v_creator_role FROM users WHERE id = p_creator_id;
    
    -- Start transaction
    START TRANSACTION;
    
    -- Create new conversation
    INSERT INTO conversations (title, type, created_by, application_id, created_at, updated_at, last_message_at)
    VALUES (p_title, 'group', p_creator_id, p_application_id, NOW(), NOW(), NOW());
    
    -- Get the new conversation ID
    SET p_conversation_id = LAST_INSERT_ID();
    
    -- Add creator as participant
    INSERT INTO conversation_participants (conversation_id, user_id, role, joined_at)
    VALUES (p_conversation_id, p_creator_id, v_creator_role, NOW());
    
    -- Add system message indicating group creation
    INSERT INTO messages (conversation_id, user_id, message, is_system_message, created_at)
    VALUES (p_conversation_id, p_creator_id, CONCAT('Group conversation "', p_title, '" created'), 1, NOW());
    
    COMMIT;
END //
DELIMITER ;

-- Create view for conversation summaries
CREATE OR REPLACE VIEW conversation_summaries AS
SELECT 
    c.id AS conversation_id,
    c.title,
    c.type,
    c.application_id,
    c.booking_id,
    c.organization_id,
    o.name AS organization_name,
    c.created_by,
    c.created_at,
    c.last_message_at,
    CASE 
        WHEN c.type = 'direct' THEN 
            (SELECT CONCAT(u.first_name, ' ', u.last_name)
             FROM conversation_participants cp
             JOIN users u ON cp.user_id = u.id
             WHERE cp.conversation_id = c.id 
             AND cp.user_id <> c.created_by
             AND cp.left_at IS NULL
             LIMIT 1)
        ELSE c.title
    END AS display_name,
    (SELECT COUNT(DISTINCT cp.id) 
     FROM conversation_participants cp 
     WHERE cp.conversation_id = c.id AND cp.left_at IS NULL) AS participant_count,
    (SELECT COUNT(m.id) 
     FROM messages m 
     WHERE m.conversation_id = c.id AND m.deleted_at IS NULL) AS message_count,
    (SELECT message 
     FROM messages 
     WHERE conversation_id = c.id AND deleted_at IS NULL 
     ORDER BY created_at DESC LIMIT 1) AS last_message,
    (SELECT user_id 
     FROM messages 
     WHERE conversation_id = c.id AND deleted_at IS NULL 
     ORDER BY created_at DESC LIMIT 1) AS last_message_user_id,
    (SELECT CONCAT(u.first_name, ' ', u.last_name)
     FROM messages m
     JOIN users u ON m.user_id = u.id
     WHERE m.conversation_id = c.id AND m.deleted_at IS NULL 
     ORDER BY m.created_at DESC LIMIT 1) AS last_message_user_name,
    (SELECT b.reference_number
     FROM bookings b
     WHERE b.id = c.booking_id) AS booking_reference
FROM 
    conversations c
JOIN
    organizations o ON c.organization_id = o.id
WHERE 
    c.deleted_at IS NULL;

-- Create view for unread messages by user
CREATE OR REPLACE VIEW unread_messages_by_user AS
SELECT 
    cp.user_id,
    cp.conversation_id,
    COUNT(m.id) AS unread_count,
    MAX(m.created_at) AS latest_unread_at
FROM 
    conversation_participants cp
JOIN 
    messages m ON cp.conversation_id = m.conversation_id
LEFT JOIN 
    message_read_status mrs ON m.id = mrs.message_id AND mrs.user_id = cp.user_id
WHERE 
    m.user_id != cp.user_id
    AND cp.left_at IS NULL
    AND m.deleted_at IS NULL
    AND mrs.id IS NULL
GROUP BY 
    cp.user_id, cp.conversation_id;

-- Indexes for performance
CREATE INDEX idx_conversations_deleted_type ON conversations(deleted_at, type);
CREATE INDEX idx_messages_deleted_created ON messages(deleted_at, created_at);
CREATE INDEX idx_participants_user_left ON conversation_participants(user_id, left_at);

-- Create view for organization conversations
CREATE OR REPLACE VIEW organization_conversations AS
SELECT 
    o.id AS organization_id,
    o.name AS organization_name,
    c.id AS conversation_id,
    c.title,
    c.type,
    c.booking_id,
    c.application_id,
    c.created_at,
    c.last_message_at,
    COUNT(DISTINCT cp.id) AS active_participants,
    COUNT(DISTINCT m.id) AS message_count,
    (SELECT COUNT(DISTINCT um.user_id)
     FROM unread_messages_by_user um
     WHERE um.conversation_id = c.id) AS users_with_unread
FROM 
    organizations o
JOIN 
    conversations c ON o.id = c.organization_id
LEFT JOIN 
    conversation_participants cp ON c.id = cp.conversation_id AND cp.left_at IS NULL
LEFT JOIN 
    messages m ON c.id = m.conversation_id AND m.deleted_at IS NULL
WHERE 
    c.deleted_at IS NULL
GROUP BY 
    o.id, o.name, c.id, c.title, c.type, c.booking_id, c.application_id, c.created_at, c.last_message_at;

-- Create view for user conversations within an organization
CREATE OR REPLACE VIEW user_organization_conversations AS
SELECT 
    cp.user_id,
    c.organization_id,
    c.id AS conversation_id,
    c.title,
    c.type,
    c.booking_id,
    c.application_id,
    c.last_message_at,
    cp.role AS user_role,
    IFNULL(um.unread_count, 0) AS unread_messages,
    (SELECT COUNT(DISTINCT cp2.id)
     FROM conversation_participants cp2
     WHERE cp2.conversation_id = c.id AND cp2.left_at IS NULL) AS participant_count
FROM 
    conversation_participants cp
JOIN 
    conversations c ON cp.conversation_id = c.id
LEFT JOIN 
    unread_messages_by_user um ON cp.user_id = um.user_id AND c.id = um.conversation_id
WHERE 
    cp.left_at IS NULL
    AND c.deleted_at IS NULL;

-- Create index for organization-based queries
CREATE INDEX idx_conversations_org_deleted ON conversations(organization_id, deleted_at);
CREATE INDEX idx_messages_conversation_deleted ON messages(conversation_id, deleted_at);
CREATE INDEX idx_participants_conversation_left ON conversation_participants(conversation_id, left_at);

-- Create stored procedure to automatically create a conversation for a new booking
DELIMITER //
CREATE PROCEDURE create_booking_conversation(
    IN p_booking_id INT,
    OUT p_conversation_id INT
)
BEGIN
    DECLARE v_user_id INT;
    DECLARE v_consultant_id INT;
    DECLARE v_team_member_id INT;
    DECLARE v_organization_id INT;
    DECLARE v_user_role VARCHAR(20);
    DECLARE v_consultant_role VARCHAR(20);
    DECLARE v_team_member_role VARCHAR(20);
    DECLARE v_service_name VARCHAR(255);
    DECLARE v_visa_type VARCHAR(255);
    
    -- Get booking information
    SELECT 
        b.user_id, 
        b.consultant_id, 
        b.team_member_id,
        b.organization_id,
        st.service_name,
        v.visa_type
    INTO 
        v_user_id, 
        v_consultant_id, 
        v_team_member_id,
        v_organization_id,
        v_service_name,
        v_visa_type
    FROM 
        bookings b
    JOIN 
        visa_services vs ON b.visa_service_id = vs.visa_service_id
    JOIN 
        service_types st ON vs.service_type_id = st.service_type_id
    JOIN 
        visas v ON vs.visa_id = v.visa_id
    WHERE 
        b.id = p_booking_id;
    
    -- Get user roles
    SELECT user_type INTO v_user_role FROM users WHERE id = v_user_id;
    SELECT user_type INTO v_consultant_role FROM users WHERE id = v_consultant_id;
    IF v_team_member_id IS NOT NULL THEN
        SELECT member_type INTO v_team_member_role FROM team_members WHERE id = v_team_member_id;
    END IF;
    
    -- Start transaction
    START TRANSACTION;
    
    -- Create new conversation
    INSERT INTO conversations (
        title, 
        type, 
        created_by, 
        booking_id, 
        organization_id, 
        created_at, 
        updated_at, 
        last_message_at
    )
    VALUES (
        CONCAT('Booking: ', v_service_name, ' - ', v_visa_type),
        'group',
        v_consultant_id,
        p_booking_id,
        v_organization_id,
        NOW(),
        NOW(),
        NOW()
    );
    
    -- Get the new conversation ID
    SET p_conversation_id = LAST_INSERT_ID();
    
    -- Add client as participant
    INSERT INTO conversation_participants (
        conversation_id, 
        user_id, 
        role, 
        joined_at
    )
    VALUES (
        p_conversation_id, 
        v_user_id, 
        'applicant', 
        NOW()
    );
    
    -- Add consultant as participant
    INSERT INTO conversation_participants (
        conversation_id, 
        user_id, 
        role, 
        joined_at
    )
    VALUES (
        p_conversation_id, 
        v_consultant_id, 
        'consultant', 
        NOW()
    );
    
    -- Add team member as participant if assigned
    IF v_team_member_id IS NOT NULL THEN
        SELECT member_user_id INTO @team_member_user_id 
        FROM team_members 
        WHERE id = v_team_member_id;
        
        IF @team_member_user_id IS NOT NULL THEN
            INSERT INTO conversation_participants (
                conversation_id, 
                user_id, 
                role, 
                joined_at
            )
            VALUES (
                p_conversation_id, 
                @team_member_user_id, 
                'team_member', 
                NOW()
            );
        END IF;
    END IF;
    
    -- Add system message indicating conversation creation
    INSERT INTO messages (
        conversation_id, 
        user_id, 
        message, 
        is_system_message, 
        created_at
    )
    VALUES (
        p_conversation_id, 
        v_consultant_id, 
        CONCAT('Conversation created for booking reference: ', (SELECT reference_number FROM bookings WHERE id = p_booking_id)), 
        1, 
        NOW()
    );
    
    COMMIT;
END //
DELIMITER ;

-- Create trigger to automatically create a conversation when a booking is confirmed
DELIMITER //
CREATE TRIGGER after_booking_confirmed
AFTER UPDATE ON bookings
FOR EACH ROW
BEGIN
    DECLARE v_status_name VARCHAR(50);
    DECLARE v_conversation_exists INT;
    
    -- Get the status name
    SELECT name INTO v_status_name 
    FROM booking_statuses 
    WHERE id = NEW.status_id;
    
    -- Check if booking status changed to confirmed and no conversation exists yet
    IF v_status_name = 'confirmed' AND (OLD.status_id != NEW.status_id) THEN
        -- Check if conversation already exists for this booking
        SELECT COUNT(*) INTO v_conversation_exists 
        FROM conversations 
        WHERE booking_id = NEW.id;
        
        -- If no conversation exists, create one
        IF v_conversation_exists = 0 THEN
            CALL create_booking_conversation(NEW.id, @conversation_id);
        END IF;
    END IF;
END //
DELIMITER ;

-- Create stored procedure to add a team member to a conversation
DELIMITER //
CREATE PROCEDURE add_team_member_to_conversation(
    IN p_conversation_id INT,
    IN p_team_member_id INT,
    IN p_added_by INT
)
BEGIN
    DECLARE v_user_id INT;
    DECLARE v_organization_id INT;
    DECLARE v_conversation_org_id INT;
    DECLARE v_team_member_org_id INT;
    
    -- Get team member's user ID
    SELECT member_user_id INTO v_user_id 
    FROM team_members 
    WHERE id = p_team_member_id;
    
    -- Get conversation organization ID
    SELECT organization_id INTO v_conversation_org_id 
    FROM conversations 
    WHERE id = p_conversation_id;
    
    -- Get team member's organization ID
    SELECT organization_id INTO v_team_member_org_id 
    FROM users 
    WHERE id = v_user_id;
    
    -- Check if team member and conversation belong to the same organization
    IF v_conversation_org_id = v_team_member_org_id THEN
        -- Check if team member is already a participant
        IF NOT EXISTS (
            SELECT 1 FROM conversation_participants 
            WHERE conversation_id = p_conversation_id AND user_id = v_user_id AND left_at IS NULL
        ) THEN
            -- Add team member as participant
            INSERT INTO conversation_participants (
                conversation_id, 
                user_id, 
                role, 
                joined_at
            )
            VALUES (
                p_conversation_id, 
                v_user_id, 
                'team_member', 
                NOW()
            );
            
            -- Add system message
            INSERT INTO messages (
                conversation_id, 
                user_id, 
                message, 
                is_system_message, 
                created_at
            )
            VALUES (
                p_conversation_id, 
                p_added_by, 
                CONCAT('Team member ', (SELECT CONCAT(first_name, ' ', last_name) FROM users WHERE id = v_user_id), ' added to the conversation'), 
                1, 
                NOW()
            );
        END IF;
    END IF;
END //
DELIMITER ;

-- Create stored procedure to add a consultant to a conversation
DELIMITER //
CREATE PROCEDURE add_consultant_to_conversation(
    IN p_conversation_id INT,
    IN p_consultant_id INT,
    IN p_added_by INT
)
BEGIN
    DECLARE v_organization_id INT;
    DECLARE v_conversation_org_id INT;
    DECLARE v_consultant_org_id INT;
    
    -- Get conversation organization ID
    SELECT organization_id INTO v_conversation_org_id 
    FROM conversations 
    WHERE id = p_conversation_id;
    
    -- Get consultant's organization ID
    SELECT organization_id INTO v_consultant_org_id 
    FROM users 
    WHERE id = p_consultant_id;
    
    -- Check if consultant and conversation belong to the same organization
    IF v_conversation_org_id = v_consultant_org_id THEN
        -- Check if consultant is already a participant
        IF NOT EXISTS (
            SELECT 1 FROM conversation_participants 
            WHERE conversation_id = p_conversation_id AND user_id = p_consultant_id AND left_at IS NULL
        ) THEN
            -- Add consultant as participant
            INSERT INTO conversation_participants (
                conversation_id, 
                user_id, 
                role, 
                joined_at
            )
            VALUES (
                p_conversation_id, 
                p_consultant_id, 
                'consultant', 
                NOW()
            );
            
            -- Add system message
            INSERT INTO messages (
                conversation_id, 
                user_id, 
                message, 
                is_system_message, 
                created_at
            )
            VALUES (
                p_conversation_id, 
                p_added_by, 
                CONCAT('Consultant ', (SELECT CONCAT(first_name, ' ', last_name) FROM users WHERE id = p_consultant_id), ' added to the conversation'), 
                1, 
                NOW()
            );
        END IF;
    END IF;
END //
DELIMITER ;
